---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sitecore-xp1-mssql-init
  newName: #{AZURE_CONTAINER_REGISTRY_HOSTNAME}#/sc-xp1-mssql-init
  newTag: #{BUILD_CONTAINER_REGISTRY_TAG_SITECORE_XP1}#

resources:
- mssql-init.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sitecore-mssql-init
  namespace: sitecore
  envs:
  - configmaps/sitecore.properties

secretGenerator:
- name: sitecore-mssql-init
  namespace: sitecore
  envs:
  - secrets/sitecore.properties
